### ISSUE TITLE
googlevideo resolver error with google doc urls

### ISSUE THREAD

**Issue by devilsport** [jsergio123/script.module.urlresolver#7]
What seems to happen is that https is lost somewhere on the way and then resolver.get_media_url can't open the link:

Call from Covenant Dayt catcher:
 ` calling plugin Covenant('plugin://plugin.video.covenant/','-1','?action=playItem&title=Alien%3A+Covenant&source=%5B%7B%22debrid%22%3A+%22%22%2C+%22language%22%3A+%22en%22%2C+%22url%22%3A+%22https%3A%2F%2Fdocs.google.com%2Ffile%2Fd%2F0B-29_UJNuoHBRnNYNWRpVlktclU%2Fpreview ....`

Error from googlevideo plugin:
`12:49:26.693 T:9956   ERROR: URLResolver: ResolverError Error - From: googlevideo Link: http://docs.google.com/file/d/0B-29_UJNuoHBRnNYNWRpVlktclU/preview: File not found
12:49:26.695 T:9956   DEBUG: URLResolver: Traceback (most recent call last):
                                              File "C:\Users\sschillinger\AppData\Roaming\Kodi\addons\script.module.urlresolver\lib\urlresolver\hmf.py", line 180, in resolve
                                                stream_url = resolver.get_media_url(self._host, self._media_id)
                                              File "C:\Users\sschillinger\AppData\Roaming\Kodi\addons\script.module.urlresolver\lib\urlresolver\plugins\googlevideo.py", line 80, in get_media_url
                                                raise ResolverError('File not found')
                                            ResolverError: File not found
`

**Comment by jsergio123** [comment]
Try to open your link from an incognito window.
DEBUG: Unable to play this video at this time. The number of allowed playbacks has been exceeded. Please try again later.

**Comment by devilsport** [comment]
OK, yeah, the same happens with browsers other than Chrome. Which is sort of stupid on behalf of xpau.se aka dayt, but well ... seems we need to look into the OAUTH thing ...

**Comment by jsergio123** [comment]
Agreed
