### ISSUE TITLE
vidtodo resolver error

### ISSUE THREAD

**Issue by devilsport** [jsergio123/script.module.urlresolver#8]
I checked the source HTML and all seems to be fine up to jsunpack. The post params are still in hidden elements so that should be fine. The return HTML from the POST contains packed data but there it breaks. Here is the log error:

```
ERROR: URLResolver: AttributeError Error - From: vidtodo Link: http://vidtodo.com/uhhh28b0t1kt: 'NoneType' object has no attribute 'groups'
DEBUG: URLResolver: Traceback (most recent call last):
				  File "\AppData\Roaming\Kodi\addons\script.module.urlresolver\lib\urlresolver\hmf.py", line 180, in resolve
					stream_url = resolver.get_media_url(self._host, self._media_id)
				  File "\AppData\Roaming\Kodi\addons\script.module.urlresolver\lib\urlresolver\plugins\vidtodo.py", line 40, in get_media_url
					packed = jsunpack.unpack(html)
				  File "\AppData\Roaming\Kodi\addons\script.module.urlresolver\lib\urlresolver\plugins\lib\jsunpack.py", line 40, in unpack
					payload, symtab, radix, count = _filterargs(source)
				  File "\AppData\Roaming\Kodi\addons\script.module.urlresolver\lib\urlresolver\plugins\lib\jsunpack.py", line 61, in _filterargs
					args = re.search(argsregex, source, re.DOTALL).groups()
				AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by jsergio123** [comment]
the site is having issues at the moment but they might have also removed the embed page so i will wait and see what happens before i change it over

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.urlresolver/commit/5a089fd6a2618bf1c851ac8529436711dddcd33a

**Comment by devilsport** [comment]
Cool
